trigger:
- master

resources:
- repo: self

variables:
  tag: "$(Build.SourceVersion)"

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: azure-devops-acr-service-connection
        repository: aks-reflector-go
        tags: |
          tag
