trigger:
- master

resources:
- repo: self

variables:
- group: "aks-reflector-go"
- name: "azure-arm-service-connection"
  value: "azure-devops-arm-service-connection"
- name: "AZDEV_BUILD_SOURCE_VERSION"
  value: $(Build.SourceVersion)

stages:
- stage: BuildPush
  displayName: Build and push image
  jobs:  
  - job: BuildPush
    displayName: Build and push image
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: azure-devops-acr-service-connection
        repository: aks-reflector-go
        tags: |
          $(AZDEV_BUILD_SOURCE_VERSION)
- stage: Deploy
  displayName: Deploy to K8s
  jobs:
  - job: Deploy
    displayName: Deploy to K8s
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Bash@3
      inputs:
        filePath: "scripts/tokenize.sh"
        env:
          ARGO_SP_PASSWORD: $(ARGO_SP_PASSWORD)
    - task: Kubernetes@1
      displayName: kubectl apply
      inputs:
        connectionType: Azure Resource Manager
        azureSubscriptionEndpoint: $(azure-arm-service-connection)
        azureResourceGroup: $(ARGO_RESOURCE_GROUP)
        kubernetesCluster: $(ARGO_AKS_CLUSTER_NAME)
        command: apply
        arguments: -f kubernetes/configmaps.yaml | -f kubernetes/secrets.yml | -f kubernetes/deployments.yml | -f kubernetes/services.yml | -f kubernetes/ingresses.yml
