apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-reflector-go-deployment
  labels:
    app: aks-reflector
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aks-reflector
      tier: backend
  template:
    metadata:
      labels:
        app: aks-reflector
        tier: backend
    spec:
      containers:
      - name: aks-reflector-go
        image: cloudnativegbb.azurecr.io/aks-reflector-go
        ports:
        - containerPort: 80 # {AWGO_LISTENING_PORT}
        env:
        - name: AWGO_SP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: aks-reflector-config
              key: sp-username
        - name: AWGO_AZURE_AD_TENANT
          valueFrom:
            configMapKeyRef:
              name: aks-reflector-config
              key: azure-ad-tenant
        - name: AWGO_RESOURCE_GROUP
          valueFrom:
            configMapKeyRef:
              name: aks-reflector-config
              key: resource-group
        - name: AWGO_AKS_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: aks-reflector-config
              key: aks-cluster-name
        - name: AWGO_LISTENING_PORT
          valueFrom:
            configMapKeyRef:
              name: aks-reflector-config
              key: listening-port
        - name: AWGO_SP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aks-reflector-secret
              key: sp-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
